#!/bin/bash

set -e

git clone -b develop git@github.com:DefactoSoftware/Pulslos-Leben.git pulslos.dev
git clone --depth=1 git://git.acquia.com/drupal/branches/7.x.git pulslos.dev/drupal.tmp

rm -f -r pulslos.dev/drupal.tmp/.git
mv -n pulslos.dev/drupal.tmp/* pulslos.dev
rm -f -r pulslos.dev/drupal.tmp
mkdir pulslos.dev/sites/default/files/
cp pulslos.dev/sites/default/default.settings.php pulslos.dev/sites/default/settings.php
echo "Succesfully installed dependencies!

To finish your setup:
1. Add this line to you hosts file: 127.0.0.1 pulslos.dev
2. Configure a website/virtual host in your webserver with hostname \"pulslos.dev\" pointing to the \"pulslos.dev\" folder.
3. Create an empty database or restore a backup from server
4 Visit http://pulslos.dev/ and follow instructions to complete Drupal installation"

